// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTN1Tg1Rjn7uc1hiJVMtsr8axB6HXxA08',
    appId: '1:866722511083:web:7185654c9cab7e8187e6ae',
    messagingSenderId: '866722511083',
    projectId: 'mcprj-eb9ab',
    authDomain: 'mcprj-eb9ab.firebaseapp.com',
    storageBucket: 'mcprj-eb9ab.firebasestorage.app',
    measurementId: 'G-SG72XHYQG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp29jQaSnvVgkmp1plWu0l4vd5lcSQ1e4',
    appId: '1:866722511083:android:f99753816952a4be87e6ae',
    messagingSenderId: '866722511083',
    projectId: 'mcprj-eb9ab',
    storageBucket: 'mcprj-eb9ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPxynDEkrzBUo1XJZTo9__KDe1YMHYxXI',
    appId: '1:866722511083:ios:7b2a190eccc9504e87e6ae',
    messagingSenderId: '866722511083',
    projectId: 'mcprj-eb9ab',
    storageBucket: 'mcprj-eb9ab.firebasestorage.app',
    iosBundleId: 'com.example.mcPrj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPxynDEkrzBUo1XJZTo9__KDe1YMHYxXI',
    appId: '1:866722511083:ios:7b2a190eccc9504e87e6ae',
    messagingSenderId: '866722511083',
    projectId: 'mcprj-eb9ab',
    storageBucket: 'mcprj-eb9ab.firebasestorage.app',
    iosBundleId: 'com.example.mcPrj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTN1Tg1Rjn7uc1hiJVMtsr8axB6HXxA08',
    appId: '1:866722511083:web:656fc515f88840ad87e6ae',
    messagingSenderId: '866722511083',
    projectId: 'mcprj-eb9ab',
    authDomain: 'mcprj-eb9ab.firebaseapp.com',
    storageBucket: 'mcprj-eb9ab.firebasestorage.app',
    measurementId: 'G-CZP7BEKWZN',
  );

}